### ISSUE TITLE
[BUG] egg info directory version number does not match release number

### ISSUE THREAD

**Issue by rh-rlandman** [unofficial-memsource/memsource-cli-client#3]
**Describe the bug**
Egg info directory version number does not match release number

**Affected version**
0.2

**To Reproduce**
1. Build memsource-cli-client
2. Look in /usr/lib/python3.6/site-packages/
3. Find egg info at memsource_cli-0.9-py3.6.egg-info

**Expected behavior**
Egg info should be at memsource_cli-0.2-py3.6.egg-info to match version number

**Screenshots or Traceback**
N/A

**Additional context**
N/A

**Comment by zerodayz** [comment]
@rh-rlandman 

Egg format is of `<name>-<version>-<pyVersion>.egg` from [setup.py](https://github.com/unofficial-memsource/memsource-cli-client/blob/master/setup.py) that already has fixed version.

Reason is that there was a typo in version fixed in: https://github.com/unofficial-memsource/memsource-cli-client/commit/8227868b757af4d0cc447dd290491bef9f91493d

Let me know if it's okay to close this issue.

**Comment by rh-rlandman** [comment]
All good thanks! Please go ahead and close

Any chance of a new Release with fixes for these two recent bugs please?

**Comment by zerodayz** [comment]
@rh-rlandman 
I have setup Travis-CI for automatic pypi builds on each git commit. The Pbr is taking care of Semantic versioning. Version has been changed to comply with PEP-440 https://github.com/unofficial-memsource/memsource-cli-client/commit/d1985fdfffe3b4b4decca73de85c53615d2a8e51
